# Generated by Django 3.1.5 on 2021-02-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo_list',
            new_name='Todo',
        ),
    ]
